spring.application.name=sgs-pagamentos
spring.datasource.url=jdbc:h2:mem:sgsdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Garante a execução dos scripts manuais DDL e DML exigidos
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

# Exibe as consultas SQL no console para validação da banca
spring.jpa.show-sql=true